// Generated by https://quicktype.io

export interface RandomPhoto {
  id: string;
  created_at: string;
  updated_at: string;
  promoted_at: null;
  width: number;
  height: number;
  color: string;
  description: string;
  alt_description: string;
  urls: Urls;
  links: RandomPhotoLinks;
  categories: any[];
  likes: number;
  liked_by_user: boolean;
  current_user_collections: any[];
  sponsorship: null;
  user: User;
  exif: Exif;
  location: Location;
  views: number;
  downloads: number;
}

export interface Exif {
  make: null;
  model: null;
  exposure_time: null;
  aperture: null;
  focal_length: null;
  iso: null;
}

export interface RandomPhotoLinks {
  self: string;
  html: string;
  download: string;
  download_location: string;
}

export interface Location {
  title: null;
  name: null;
  city: null;
  country: null;
  position: Position;
}

export interface Position {
  latitude: null;
  longitude: null;
}

export interface Urls {
  raw: string;
  full: string;
  regular: string;
  small: string;
  thumb: string;
}

export interface User {
  id: string;
  updated_at: string;
  username: string;
  name: string;
  first_name: string;
  last_name: string;
  twitter_username: null;
  portfolio_url: null;
  bio: null;
  location: string;
  links: UserLinks;
  profile_image: ProfileImage;
  instagram_username: string;
  total_collections: number;
  total_likes: number;
  total_photos: number;
  accepted_tos: boolean;
}

export interface UserLinks {
  self: string;
  html: string;
  photos: string;
  likes: string;
  portfolio: string;
  following: string;
  followers: string;
}

export interface ProfileImage {
  small: string;
  medium: string;
  large: string;
}
